# Generated by Django 3.2a1 on 2021-03-31 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Radiation_measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=40)),
                ('brand', models.CharField(max_length=40)),
                ('measured_value_EF', models.CharField(default='EF V/m', editable=False, max_length=10)),
                ('EF_measured_value', models.CharField(max_length=30)),
                ('measured_value_MF', models.CharField(default='MF μT', editable=False, max_length=10)),
                ('MF_measured_value', models.CharField(max_length=30)),
                ('measured_value_Power', models.CharField(default='Power mW/cm2', editable=False, max_length=10)),
                ('power_measured_value', models.CharField(max_length=30)),
                ('alarm', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radiation_measurement.type')),
            ],
        ),
    ]
