# Generated by Django 3.1.6 on 2021-02-04 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radiation_measurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radiation_measurement',
            old_name='Power_measured_value',
            new_name='power_measured_value',
        ),
    ]
