# Generated by Django 3.1.6 on 2021-02-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiation_measurement', '0002_auto_20210204_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radiation_measurement',
            old_name='instrument_name',
            new_name='type',
        ),
        migrations.AddField(
            model_name='radiation_measurement',
            name='area',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
