# Generated by Django 3.1.6 on 2021-02-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiation_measurement', '0004_auto_20210211_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiation_measurement',
            name='brand',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
