# Generated by Django 3.2a1 on 2021-03-30 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radiation_measurement', '0005_radiation_measurement_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radiation_measurement',
            old_name='EF_threshold_distance',
            new_name='alarm',
        ),
        migrations.RemoveField(
            model_name='radiation_measurement',
            name='threshold_distance_EF',
        ),
    ]
